--[[ -----------------------------------
 #  Модуль выдачи сообщений
 #  for Lost Path
 #  author : b4d1k
 #  date   : 11.11.2017
 #  file   : lostpath_message.script 
]]-- -----------------------------------

-- ---------------------------------------------------------------------------------
-- Сообщение когда взяли Шрама
function send_message_shram()
	news_manager.send_tip(db.actor, "%c[255,255,160,0]System:\\n%c[255,160,160,160]You took a companion %c[255,255,255,160]Scar%c[255,160,160,160]", nil, nil, nil, nil)
	xr_sound.set_sound_play(db.actor:id(), "pda_tips")
end
-- ---------------------------------------------------------------------------------

-- ---------------------------------------------------------------------------------
-- Сообщение когда взяли Зулуса
function send_message_zulus()
	news_manager.send_tip(db.actor, "%c[255,255,160,0]System:\\n%c[255,160,160,160]You took a companion %c[255,255,255,160]Zulu%c[255,160,160,160]", nil, nil, nil, nil)
	xr_sound.set_sound_play(db.actor:id(), "pda_tips")
end
-- ---------------------------------------------------------------------------------